#spring.application.name=module06-file-upload
#spring.servlet.multipart.location=C:/upload-files
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
#spring.mvc.static-path-pattern=/static/**

spring:
  servlet:
    multipart:
      location: C:/upload-files
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name:   module06-file-upload
  mvc:
    static-path-pattern: /static/**